name: Clang Format Check

on:
  push:
  pull_request:

jobs:
  clang-format:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install clang-format
        run: sudo apt-get update && sudo apt-get install -y clang-format

      - name: Check formatting
        run: |
          FILES=$(find . -name '*.cpp' -or -name '*.hpp' -or -name '*.h')
          clang-format --dry-run --Werror $FILES
