name: CTest

on:
  push:
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install dependencies
        run: sudo apt-get update && sudo apt-get install -y cmake build-essential

      - name: Configure, build, and run tests
        run: |
          mkdir -p build
          cd build
          cmake ..
          make -j$(nproc)
          ctest --output-on-failure
